package com.apex.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String firstname;
    /** Not-null value. */
    private String surname;
    /** Not-null value. */
    private String nic;
    /** Not-null value. */
    private String age;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String firstname, String surname, String nic, String age) {
        this.id = id;
        this.firstname = firstname;
        this.surname = surname;
        this.nic = nic;
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirstname() {
        return firstname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /** Not-null value. */
    public String getSurname() {
        return surname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /** Not-null value. */
    public String getNic() {
        return nic;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNic(String nic) {
        this.nic = nic;
    }

    /** Not-null value. */
    public String getAge() {
        return age;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAge(String age) {
        this.age = age;
    }

}
